apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-secret-app
  template:
    metadata:
      labels:
        app: go-secret-app
    spec:
      containers:
      - name: go-secret-app
        image: go-secret-app:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: my-secret

---
apiVersion: v1
kind: Service
metadata:
  name: go-secret-app-service
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: go-secret-app